language: node_js
node_js: stable

# S: Build Lifecycle
install:
#  - npm install -g hexo
#  - npm install -g hexo-deploy-git
  - npm install


before_script:
 # - npm install -g gulp
#   - npm install -g hexo
   - hexo -v

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "cyddgh"
  - git config user.email "623193096@qq.com"
  - git add .
  - git commit -m "Update blog!"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master  #GITHUB_TOKEN为在TravisCI中添加的来自Github的授权Token，见上一步

branches:
  only:
    - hexo

# 创建全局变量，与GithubPage仓库ssh地址一致
env:
 global:
   - GH_REF: git@github.com:cyddgh/cyddgh.github.io.git